version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
      POSTGRES_DB: test-service
      PGDATA: /var/lib/postgresql/data/test
    ports:
      - "5432:5432"
    volumes:
      - ptkab_pgdb_data:/var/lib/postgresql/data/test
    networks:
      - ptkab-network

  app:
    image: ramdanariadi/pt-kab-test:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/test-service
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: public
    networks:
      - ptkab-network
    ports:
      - "10000:8080"
    depends_on:
      - db
networks:
  ptkab-network:
    driver: bridge

volumes:
  ptkab_pgdb_data:
